---
openapi: 3.0.3

servers:
  - url: /v1

info:
  title: Lupi Game API
  description: |
    # Least Unique Positive Integer (Lupi)

    Lupi is a fun game, that has been studied a lot and has some maths
    behind how people behave and what really is optimal in some respect.

    ## The Rules of the Game

    - Lupi is a multiplayer game
    - each player picks a positive integer
    - the lowest unique integer wins

  license:
    name: Unlicense
    url: https://unlicense.org/
  version: 1.0.0

tags:
  - name: game
    description: Playing the game
  - name: stats
    description: Game statistics

paths:
  /rounds:
    get:
      tags: [stats]
      description: Get all known rounds
      operationId: lupi.api.get_rounds
      responses:
        200:
          description: List of all round ids
          content:
            application/json:
              schema:
                type: array
                items:
                  type: integer

    post:
      tags: [game]
      description: Creates a new game round
      operationId: lupi.api.create_round
      responses:
        201:
          description: A new game round was created
          content:
            application/json:
              schema:
                type: integer
        409:  # conflict
          description: An active game round already exists

  /votes:
    post:
      tags: [game]
      description: Register a user vote
      operationId: lupi.api.add_vote
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - round
                - user
                - vote
              properties:
                round:
                  $ref: "#/components/schemas/round"
                user:
                  type: string
                vote:
                  $ref: "#/components/schemas/vote"
      responses:
        200:
          description: Vote accepted
        409:  # conflict
          description: Already voted or the round is already closed
        404:
          description: Round is not available

  /rounds/{round}/is_completed:
    parameters:
      - $ref: "#/components/parameters/round"
    put:
      tags: [game]
      description: Completes a round, calculates winner
      operationId: lupi.api.set_round_is_completed
      requestBody:
        content:
          application/json:
            schema:
              type: boolean
      responses:
        204:
          description: |
            Either of
            - game round was completed
            - no change
        409:  # conflict
          description: |
            When value is false and the round is already completed.

            Reopening a round is not supported because completed
            rounds make information public which would allow one
            to win - it is a possible cheating vector.
        404:
          description: Round is not available

  /rounds/current/id:
    get:
      tags: [game]
      description: Return the current round id
      operationId: lupi.api.get_current_round_id
      responses:
        200:
          description: Current round id
          content:
            application/json:
              schema:
                type: integer
                example: 12
        404:
          description: Never started a round yet

  /rounds/{round}/result:
    parameters:
      - $ref: "#/components/parameters/round"
    get:
      tags: [stats, game]
      description: Get round result
      operationId: lupi.api.get_round_result
      responses:
        200:
          description: results
          content:
            application/json:
              schema:
                type: object
                required:
                  - is_completed
                properties:
                  is_completed:
                    type: boolean
                  winner:
                    type: string
                    example: winning-user
                  vote:
                    $ref: "#/components/schemas/vote"
        404:
          description: Round/its result is not available

  /rounds/{round}:
    parameters:
      - $ref: "#/components/parameters/round"
    get:
      tags: [stats]
      description: Get round details
      operationId: lupi.api.get_round
      responses:
        200:
          description: Details of round
          content:
            application/json:
              schema:
                type: object
                required:
                  - start_date
                  - is_completed
                properties:
                  start_date:
                    type: string
                    format: date-time
                  end_date:
                    type: string
                    format: date-time
                  is_completed:
                    type: boolean
                  players:
                    type: integer
                    minimum: 0
        404:
          description: Round is not available

components:
  parameters:
    round:
      name: round
      in: path
      required: true
      schema:
        $ref: "#/components/schemas/round"
  schemas:
    round:
      type: string
      pattern: "^current|\\d+$"
      default: current
    vote:
      type: integer
      minimum: 1
      example: 2
