FROM python:3.8-slim

# https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#user
RUN groupadd -r lupi && useradd --no-log-init -r -g lupi lupi

WORKDIR /code
COPY scripts/wait-for-http /code/

COPY lupi_ui/requirements.txt /code/lupi_ui/
COPY lupi_game_client /code/lupi_game_client
RUN cd lupi_ui && pip install -r requirements.txt

EXPOSE 8080
USER lupi
CMD ./wait-for-http game_server:8080 && \
    gunicorn -w 4 --bind 0.0.0.0:8080 'lupi_ui.app:create_app()'

COPY lupi_ui /code/lupi_ui
