version: "3.8"

services:
  game_server:
    volumes:
      - ./lupi_game_server:/code/lupi_game_server
  ui:
    volumes:
      - ./lupi_ui:/code/lupi_ui
      - ./lupi_game_client:/code/lupi_game_client
  info:
    image: python:3.8-slim
    command:
      - python
      - -c
      - |
        from socket import gethostbyname as ip
        print(f"""\
        IP addresses of containers:
          db:          {ip('db')}
          game_server: {ip('game_server')}
          ui:          {ip('ui')}\n""")
        print(f"""\
        Accessible internal services of interest:
          game_server API:   http://{ip('game_server')}:8080/v1/ui
          ui (in container): http://{ip('ui')}:8080\n""")
    networks:
      - internal
    depends_on:
      - db
      - game_server
      - ui
  ui-tests:
    build:
      context: .
      dockerfile: Dockerfile.ui-tests
    image: lupi-ui-test
    volumes:
      - ./lupi_ui:/code/lupi_ui
      - ./lupi_game_client:/code/lupi_game_client
    depends_on:
      - ui
    networks:
      - internal