FROM python:3.8-slim
RUN apt-get update && apt-get install -y iputils-ping net-tools

# Add docker-compose-wait tool
ENV WAIT_VERSION 2.7.3
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/$WAIT_VERSION/wait /wait
RUN chmod +x /wait

# https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#user
RUN groupadd -r lupi && useradd --no-log-init -r -g lupi lupi

WORKDIR /code
COPY lupi_ui/requirements.txt /code/lupi_ui/
COPY lupi_game_client /code/lupi_game_client
RUN cd lupi_ui && pip install -r requirements.txt

EXPOSE 8080
USER lupi
CMD /wait && gunicorn -w 4 --bind 0.0.0.0:8080 'lupi_ui.app:create_app()'

COPY lupi_ui /code/lupi_ui
