version: "3.8"

services:
  game_server:
    volumes:
      - ./game_server:/code/game_server
  ui:
    volumes:
      - ./ui:/code/ui
  info:
    image: python:3.8-slim
    command:
      - python
      - -c
      - |
        from socket import gethostbyname as h
        print(f"""\
        IP addresses of containers:
          db:          {h('db')}
          game_server: {h('game_server')}
          ui:          {h('ui')}\n""")
        print(f"""\
        Accessible internal services of interest:
          game_server API:   http://{h('game_server')}:8080/v1/ui
          ui (in container): http://{h('ui')}:8080\n""")
    networks:
      - internal
    depends_on:
      - db
      - game_server
      - ui
