# coding: utf-8

"""
    Lupi Game API

    # Least Unique Positive Integer (Lupi)  Lupi is a fun game, that has been studied a lot and has some maths behind how people behave and what really is optimal in some respect.  ## The Rules of the Game  - Lupi is a multiplayer game - each player picks a positive integer - the lowest unique integer wins   # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import lupi_game_client
from lupi_game_client.models.paging import Paging  # noqa: E501
from lupi_game_client.rest import ApiException

class TestPaging(unittest.TestCase):
    """Paging unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Paging
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = lupi_game_client.models.paging.Paging()  # noqa: E501
        if include_optional :
            return Paging(
                before = 12, 
                page_size = 1
            )
        else :
            return Paging(
                before = 12,
                page_size = 1,
        )

    def testPaging(self):
        """Test Paging"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
