---
openapi: 3.0.3

servers:
  - url: /v1

info:
  title: Lupi Game API
  description: |
    # Least Unique Positive Integer (Lupi)

    Lupi is a fun game, that has been studied a lot and has some maths
    behind how people behave and what really is optimal in some respect.

    ## The Rules of the Game

    - Lupi is a multiplayer game
    - each player picks a positive integer
    - the lowest unique integer wins

  license:
    name: Unlicense
    url: https://unlicense.org/
  version: 1.0.0

tags:
  - name: game
    description: Playing the game
  - name: stats
    description: Game statistics

paths:
  /rounds:
    get:
      parameters:
        - name: before
          in: query
          description: "(Paging) Return rounds before this round id"
          schema:
            type: integer
          example: 4
        - name: limit
          in: query
          description: "(Paging) Return at most this many rounds at once"
          schema:
            type: integer
            minimum: 1
            maximum: 100
          example: 25
      tags: [stats]
      description: List completed rounds, most recent first, paged
      operationId: game_server.api.get_rounds
      responses:
        200:
          description: |
            Limited list of rounds
            - round data (IDs and start date, end date, number of participants)
            - and paging link
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/rounds_response"

    post:
      tags: [game]
      description: Creates a new game round
      operationId: game_server.api.create_round
      responses:
        201:
          description: A new game round was created
          content:
            application/json:
              schema:
                type: integer
        409:  # conflict
          description: An active game round already exists

  /votes:
    post:
      tags: [game]
      description: Register a user vote
      operationId: game_server.api.add_vote
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - round
                - name
                - number
              properties:
                round:
                  $ref: "#/components/schemas/round"
                name:
                  type: string
                number:
                  $ref: "#/components/schemas/vote"
      responses:
        200:
          description: Vote accepted
        409:  # conflict
          description: Already voted or the round is already closed
        404:
          description: Round is not available

  /rounds/{round}/is_completed:
    parameters:
      - $ref: "#/components/parameters/round"
    put:
      tags: [game]
      description: Completes a round, calculates winner
      operationId: game_server.api.complete_round
      requestBody:
        content:
          application/json:
            schema:
              type: boolean
      responses:
        204:
          description: |
            Either of
            - game round was completed
            - no change
        409:  # conflict
          description: |
            When value is false and the round is already completed.

            Reopening a round is not supported because completed
            rounds make information public which would allow one
            to win - it is a possible cheating vector.
        404:
          description: Round is not available

  /rounds/current/id:
    get:
      tags: [game]
      description: Return the current round id
      operationId: game_server.api.get_current_round_id
      responses:
        200:
          description: Current round id
          content:
            application/json:
              schema:
                type: integer
                example: 12
        404:
          description: Not started a round yet

  /rounds/{round}/result:
    parameters:
      - $ref: "#/components/parameters/round"
    get:
      tags: [stats, game]
      description: Get round result
      operationId: game_server.api.get_round_result
      responses:
        200:
          description: results
          content:
            application/json:
              schema:
                type: object
                required:
                  - is_completed
                properties:
                  is_completed:
                    type: boolean
                  winner:
                    type: string
                    example: winning-user
                  vote:
                    $ref: "#/components/schemas/vote"
        404:
          description: Round/its result is not available

  /rounds/{round}:
    parameters:
      - $ref: "#/components/parameters/round"
    get:
      tags: [stats]
      description: Get round details
      operationId: game_server.api.get_round
      responses:
        200:
          description: Details of round
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/stat_round"
        404:
          description: Round is not available

components:
  parameters:
    round:
      name: round
      in: path
      required: true
      schema:
        $ref: "#/components/schemas/round"

  schemas:
    round:
      type: string
      pattern: "^current|\\d+$"
      default: current

    vote:
      type: integer
      minimum: 1
      example: 2

    stat_round:
      # IDs and start date, end date, players (=number of participants)
      type: object
      required:
        - id
        - start_date
      properties:
        id:
          type: integer
        start_date:
          type: string
          format: date-time
        end_date:
          type: string
          format: date-time
        players:
          type: integer
          minimum: 0

    rounds_response:
      type: object
      required:
        - data
      properties:
        data:
          type: array
          items:
            allOf:
              - $ref: "#/components/schemas/stat_round"
              - type: object
                required:
                  # make all properties required
                  - id
                  - start_date
                  - end_date
                  - players
        previous:
          type: string
          example: /v1/rounds?before=4
