#!/usr/bin/env python
import logging
import socket
import sys
import time

logging.basicConfig(
    level=logging.INFO,
    format='[%(asctime)s] wait-for-postgres [%(levelname)s] %(message)s')
host = sys.argv[1]
timeout = 1.0
wait = 1.0

while True:
    try:
        s = socket.create_connection((host, 5432), timeout)
        s.close()
        logging.info(f'PostgreSQL host "{host}" is ready')
        sys.exit(0)
    except socket.error:
        logging.warning(f'PostgreSQL host "{host}" is not yet available')
        time.sleep(wait)
